kind: Deployment
apiVersion: apps/v1
metadata:
  name: ds2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds2
  template:
    metadata:
      labels:
        app: ds2
    spec:
      containers:
      - name: python-container
        image: 9923/ds2:19
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        args: ["python", "ds2LogicReactive.py"]
        env:
        - name: AVG_OVER_TIME
          value: "1m"
        - name: SLEEP_TIME
          value: "20"
        - name: CONTAINER
          value: "9923/experiments:31"
        - name: JOB
          value: "ch.ethz.systems.strymon.ds2.flink.nexmark.queries.Query1KafkaSource"  
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONIOENCODING
          value: "UTF-8" 
        - name: MIN_REPLICAS
          value: "1"
        - name: MAX_REPLICAS
          value: "16"
        - name: COOLDOWN
          value: "240s"
        - name: BIDSQUERY
          value: "yes"
        - name: QUERY
          value: "query-1"
        - name: OVERPROVISIONING_FACTOR
          value: "1.2"
        - name: LAG_PROCESSING_TIME
          value: "120"

