kind: Deployment
apiVersion: apps/v1
metadata:
  name: workbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workbench
  template:
    metadata:
      labels:
        app: workbench
    spec:
      containers:
      - name: workbench-container
        image: 9923/workbench:14
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 2000m
            memory: 2000Mi
          limits:
            cpu: 2500m
            memory: 2500Mi
        env:
        args: ["mvn", "exec:java", "-Dexec.mainClass=ch.ethz.systems.strymon.ds2.flink.nexmark.sources.BidPersonGeneratorKafka", "-Dexec.args=--mode 1 --amplitude 80000 --y-shift 120000 --period 60 --bids-only 0"]
        # args: ["mvn", "exec:java", "-Dexec.mainClass=ch.ethz.systems.strymon.ds2.flink.nexmark.sources.BidSourceFunctionGeneratorKafka", "-Dexec.args=--mode 1 --amplitude 80000 --y-shift 120000 --period 60"]
        # args: ["mvn", "exec:java", "-Dexec.mainClass=ch.ethz.systems.strymon.ds2.flink.nexmark.sources.BidSourceFunctionGeneratorKafka", "-Dexec.args=--mode 0 --rate 200000"]

      
